name: Test & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '16'
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Cache NPM packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.npm/
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install and Build
        run: |
          npm install
          npm run build
          npm run coverage
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: coverage/cobertura-coverage.xml
          output: both
          badge: true
          format: markdown
          indicators: true
      - name: Move coverage markdown into directory
        run: |
          mv code-coverage-results.md coverage
      - name: Upload test coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage

  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "r2-quotes"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
