name: Test & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '16'
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Cache NPM packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.npm/
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install and Build
        run: |
          npm install
          npm run coverage
      - name: Upload test coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage

  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: deploy
          force: true